#!/bin/sh
#Sebastian Lindau-Skands ©2022
#@lynet_101


#Easy GPU management for hybrid graphic setups | ui

echo 'Supported modes are: On [int. screen may turn off] | Hybrid [Run programs via prime-run | hdmi may not work] | Off [turns off nvidia-gpu | hdmi may not work]'
read -p "Which state do you wish for the gpu to be in: " act
mv /etc/fun/state /etc/fun/prev_state && echo $act >> /etc/fun/state
/etc/fun/fun-daemon-script
